# 스크립트 작성 : 박동권(dk@devrock.co.kr)

# 현재 내 파일이 있는 위치로 이동(.sh)
cd $(dirname "$0")


# swagger-codegen으로 모델 등등을 생성합니다. ( https://github.com/swagger-api/swagger-codegen )
# 설치되어있지 않다면 설치 ( brew install swagger-codegen )
swagger-codegen generate -i http://boostdev.lysn.com/v2/api-docs?group=API -l swift4 -o swagger


# 치환할 원래 문자열, 치환후의 문자열
FINDMARK=': Codable {'
FINDMARKESC=': BaseModel {'

# codegen이 만들어준 파일들 중의 모델 디렉토리
CP_FROM='./swagger/SwaggerClient/Classes/Swaggers/Models'
# 모델을 프로젝트에 복사한 후 작업을 하게 됩니다.
CP_TO='./BoostMINI/BoostMINI/Classes/Model/Generated'
# 타임스탬프 (Generated가 폴더레퍼런스이므로 그 상위 폴더에 저장해주는 센스.)
CP_TIMESTAMP='./BoostMINI/BoostMINI/Classes/Model/zGeneratedDate.md'

# # ls 목록에서 total 144, ./, ../ 요 세 줄을 빼야 파일개수
CNTFROM=$((0+$(find $CP_FROM/ -type f -maxdepth 1 | wc -l) ))
echo "생성된 파일 : $CNTFROM 개"


TEST_FILENAME="Notice.swift"
TEST_LINE="11"

# 폴더없으면 생성
mkdir "$CP_TO" 2>>/dev/null

# 기존 파일들 모두 삭제... (추가로 만든 파일들도 삭제됩니다. 알고계시길!!)
for X in $(find $CP_TO/*.swift -type f -maxdepth 1); do rm "$X"; done;


# 복사

# 코드 검색 조건 (Codable)에 해당하는 실제 모델이 파일들만 복사.
#CNT=0
#for X in $(grep -IRil --include=\*.swift "$FINDMARK" "$CP_FROM" 2<</dev/null); do CNT=$((CNT+1)); cp "$X" "$CP_TO"; done;
#for X in $(grep -IRil --include=\*.swift "$FINDMARK" "$CP_FROM" 2<</dev/null); do cp "$X" "$CP_TO"; echo $X; done;
for X in $(grep -IRil --include=\*.swift "$FINDMARK" "$CP_FROM" 2<</dev/null); do cp "$X" "$CP_TO"; done;

# 모델 타입이지만 쓸 일이 없어보이는 녀석이 더러 있다. 수작업 제거.
# RedirectView, ApplicationContext

rm "$CP_TO/RedirectView.swift" 2>>/dev/null
rm "$CP_TO/ApplicationContext.swift" 2>>/dev/null
rm "$CP_TO/ClassLoader.swift" 2>>/dev/null
rm "$CP_TO/*BeanFactory.swift" 2>>/dev/null

# 폴더내의 최종 swift 파일 카운트. (기존에 파일이 있었다면 이 역시 같이 카운트)
CNTTO=$((0+$(find $CP_TO/*.swift -type f -maxdepth 1 | wc -l) ))

#//CNT=$((CNT-3))

echo "복사되어지는 모델 폴더 : `pwd`/$CP_TO"
echo "모델 폴더의 현재 swift 파일 : $CNTTO 개"


echo ""
TIMESTAMP=`date`
`echo -e "Generated 디렉토리 내부는 자동생성되는 디렉토리입니다.\n 해당 디렉토리 내에서는 파일 생성,수정,삭제 등등을 하지말아주시기 바랍니다.\n- Generated by codegenRestAPI.sh\n- Contact : 박동권 (dk@devrock.co.kr)\n\n**생성날짜**\n$TIMESTAMP" > $CP_TIMESTAMP`
echo "타임스탬프 : $TIMESTAMP"
echo "스탬프 저장위치 : $CP_TIMESTAMP"
echo ""



IFS=$'\n'

# copy from src
echo "* 소스 치환 (Codable -> BaseModel)"
echo "원본의 소스 중 일부 : `head -n $TEST_LINE $CP_TO/$TEST_FILENAME | tail -n 1` ... }"


for X in $CP_TO/*.swift; do sed -i '' -e "s/$FINDMARK/$FINDMARKESC/g" $X; done 


echo "변경된 소스 중 일부 : `head -n $TEST_LINE $CP_TO/$TEST_FILENAME | tail -n 1` ... }"
echo   
echo   


