disabled_rules: # 실행에서 제외할 룰 식별자들
  - colon
  - comma
  - control_statement
  - block_based_kvo # swift 3.2
  - closure_parameter_position
  - discarded_notification_center_observer
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - nesting
  - type_body_length
  - type_name
  - trailing_newline
  - trailing_comma
  - trailing_whitespace
  - weak_delegate
  - empty_count
  - missing_docs
  - vertical_whitespace
  - line_length
  - private_outlet
  # 사용 가능한 모든 룰은 swiftlint rules 명령으로 확인 가능
opt_in_rules: # 일부 룰은 옵트 인 형태로 제공
  - empty_count
  - force_unwrapping
  - private_outlet
line_length: 110
type_body_length:
  warning: 300
  error: 400
included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨
excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
  - Carthage/
  - Frameworks/
  - boostMINI.playground/
  - Library/Strings.swift
  - bin/strings.swift
  - Pods/

# 설정 가능한 룰은 이 설정 파일에서 커스터마이징 가능
# 경고나 에러 중 하나를 발생시키는 룰은 위반 수준을 설정 가능
force_cast: warning # 암시적으로 지정
force_try:
  severity: warning # 명시적으로 지정
# 경고 및 에러 둘 다 존재하는 룰의 경우 값을 하나만 지정하면 암시적으로 경고 수준에 설정됨
line_length: 110
# 값을 나열해서 암시적으로 양쪽 다 지정할 수 있음
type_body_length:
  - 300 # 경고
  - 400 # 에러
# 둘 다 명시적으로 지정할 수도 있음
file_length:
  warning: 500
  error: 1200
# 네이밍 룰은 경고/에러에 min_length와 max_length를 각각 설정 가능
# 제외할 이름을 설정할 수 있음
type_name:
  min_length: 4 # 경고에만 적용됨
  max_length: # 경고와 에러 둘 다 적용
    warning: 40
    error: 50
  excluded: iPhone # 제외할 문자열 값 사용
identifier_name:
  min_length: # min_length에서
    error: 4 # 에러만 적용
  excluded: # 제외할 문자열 목록 사용
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # 보고 유형 (xcode, json, csv, checkstyle, junit, html, emoji)
custom_rules:
  localized_lensing:
    name: "Localized Lensing"
    regex: '\.~\s+Strings\s*\.'
    message: "Capture calls to `Strings` functions using `%~ { _ in Strings... }`"
    severity: error
  record_mode_prohibited:
    name: "Record Mode Prohibited"
    regex: "recordMode = true"
    message: "Do not use `recordMode = true`."
    severity: error
# pirates_beat_ninjas: # 룰 식별자
#     included: ".*.swift" # 린트 실행시 포함할 경로를 정의하는 정규표현식. 선택 가능.
#     name: "Pirates Beat Ninjas" # 룰 이름. 선택 가능.
#     regex: "([n,N]inja)" # 패턴 매칭
#     match_kinds: # 매칭할 SyntaxKinds. 선택 가능.
#       - comment
#       - identifier
#     message: "Pirates are better than ninjas." # 위반 메시지. 선택 가능.
#     severity: error # 위반 수준. 선택 가능.
#   no_hiding_in_strings:
#     regex: "([n,N]inja)"
#     match_kinds: string
