# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

def open_sources
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for BoostMINI
  pod 'SwiftLint'
  # pod 'RealReachability'
  # pod 'Realm'
  pod 'SideMenu'
  pod 'Toaster'
  pod 'SwiftyBeaver', '~> 1.5.0'
  pod 'R.swift'


  #	pod 'ImageViewer', '>= 5.0'
  pod 'Kingfisher', '~> 4.0'

  pod 'UIColor_Hex_Swift', '~> 4.0.1'
  pod 'TransitionButton'

  pod 'TOCropViewController'
  #
  #	pod 'ReSwift'
  #	pod 'ReSwiftRouter', '~> 0.5.0'
  #	#pod 'ReSwiftRecorder'
  #
  
  pod 'Alamofire', '~> 4.6'
  pod 'AlamofireImage'
  #pod 'CodableAlamofire', '~> 1.1.0'	#// 내장 사용
  
  #
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  # ReactorKit
  pod 'ReactorKit'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Moya-ModelMapper/RxSwift'
  pod 'RxOptional'
  pod 'RxViewController'

# BluetoothKt
    pod 'RxBluetoothKit'

#  FaceBook
#   #pod 'FBSDKLoginKit', '~> 4.18.0' # too old
#	pod 'FacebookCore'
#	pod 'FacebookLogin'

# for Permission
    pod 'JuseongJee_RxPermission/Bluetooth',   :git => 'https://github.com/JuseongJee/RxPermission.git'
    pod 'JuseongJee_RxPermission/Camera',      :git => 'https://github.com/JuseongJee/RxPermission.git'
    pod 'JuseongJee_RxPermission/Photos',      :git => 'https://github.com/JuseongJee/RxPermission.git'
    pod 'JuseongJee_RxPermission/Notifications',:git => 'https://github.com/JuseongJee/RxPermission.git'

# for Analytics

# for Debugging
	pod 'Fabric'
	pod 'Crashlytics'
    pod 'FLEX', 	:configurations => ['Debug']  #hslee add, https://github.com/Flipboard/FLEX
    # pod 'Buglife',  :configurations => ['Debug', 'DebugOnLive', 'Release', 'Stage']  #hslee add, https://www.buglife.com

end


target 'BoostMINI' do
	open_sources
end

 target 'BoostMINITests' do
 	open_sources
	#pod 'RxBlocking', '~> 4.0'
	#pod 'RxTest',     '~> 4.0'
 end

 target 'BoostMINIUITests' do
 	open_sources
#	pod 'RxBlocking', '~> 4.0'
#	pod 'RxTest',     '~> 4.0'
 end


post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '4.0'
		end
	end
end
