//
// AppsGetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class AppsGetResponse: Codable {

    public var forceUpdate: Bool?
    public var id: Int64?
    public var version: String?

    public init() {}

}
