//
// ClassLoader.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ClassLoader: Codable {

    public var parent: ClassLoader?

    public init() {}

}
