//
// HelpGetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class HelpGetResponse: Codable {

    public var list: PageHelp?

    public init() {}

}
