//
// NoticesGetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class NoticesGetResponse: Codable {

    public var list: PageNotice?

    public init() {}

}
