//
// Environment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Environment: Codable {

    public var activeProfiles: [String]?
    public var defaultProfiles: [String]?

    public init() {}

}
