//
// SettingsGetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SettingsGetResponse: Codable {

    public var alarm: Bool?
    public var skin: [Skin]?
    public var userName: String?

    public init() {}

}
