//
// Help.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Help: Codable {

    public var content: String?
    public var id: Int64?
    public var title: String?

    public init() {}

}
