//
// RedirectView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RedirectView: Codable {

    public var applicationContext: ApplicationContext?
    public var attributesMap: Any?
    public var beanName: String?
    public var contentType: String?
    public var exposePathVariables: Bool?
    public var hosts: [String]?
    public var propagateQueryProperties: Bool?
    public var redirectView: Bool?
    public var requestContextAttribute: String?
    public var staticAttributes: Any?
    public var url: String?

    public init() {}

}
