//
// AutowireCapableBeanFactory.swift
//
// Generated by swagger-codegen
// Modified by dk (dk@devrock.co.kr)
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


// public typealias AutowireCapableBeanFactory = Any
