//
// CommonNumberGetResponse.swift
//
// Generated by swagger-codegen
// Modified by dk (dk@devrock.co.kr)
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CommonNumberGetResponse: BaseModel {
	// autogen apiList protocol
	static var apiList: [String: APIRequest] = CommonNumberGetResponse.buildApiRequests()


    public var selected: Int32?

    public init() {}

}
