//
// CommonNumberGetResponse.swift
//
// Generated by swagger-codegen
// Modified by dk (dk@devrock.co.kr)
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CommonNumberGetResponse: Codable {

    public var selected: Int32?

    public init() {}

}
