//
// CommonBooleanGetResponse.swift
//
// Generated by swagger-codegen
// Modified by dk (dk@devrock.co.kr)
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CommonBooleanGetResponse: Codable {

    public var alarm: Bool?

    public init() {}

}
