//
// SettingsGetResponse.swift
//
// Generated by swagger-codegen
// Modified by dk (dk@devrock.co.kr)
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SettingsGetResponse: Codable {

    public var alarm: Bool?
    public var skins: [Skin]?
    public var userName: String?

    public init() {}

}
