//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// Modified by dk (dk@devrock.co.kr)
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import RxSwift



open class DefaultAPI {
    /**
     콘서트 정보 가져오기
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getConcertsUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String, completion: @escaping ((_ data: ConcertsGetResponse?,_ error: Error?) -> Void)) {
        getConcertsUsingGETWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     콘서트 정보 가져오기
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - returns: Observable<ConcertsGetResponse>
     */
    open class func getConcertsUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> Observable<ConcertsGetResponse> {
        return Observable.create { observer -> Disposable in
            getConcertsUsingGET(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     콘서트 정보 가져오기
     - GET /concerts
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 

     - returns: RequestBuilder<ConcertsGetResponse> 
     */
    open class func getConcertsUsingGETWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> RequestBuilder<ConcertsGetResponse> {
        let path = "/concerts"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ConcertsGetResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     도움말 목록 가져오기
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter lastId: (query)  (optional)
     - parameter size: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getHelplistUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String, lastId: Int64? = nil, size: Int32? = nil, completion: @escaping ((_ data: HelpGetResponse?,_ error: Error?) -> Void)) {
        getHelplistUsingGETWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, lastId: lastId, size: size).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     도움말 목록 가져오기
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter lastId: (query)  (optional)
     - parameter size: (query)  (optional)
     - returns: Observable<HelpGetResponse>
     */
    open class func getHelplistUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String, lastId: Int64? = nil, size: Int32? = nil) -> Observable<HelpGetResponse> {
        return Observable.create { observer -> Disposable in
            getHelplistUsingGET(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, lastId: lastId, size: size) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     도움말 목록 가져오기
     - GET /menus/help
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter lastId: (query)  (optional)
     - parameter size: (query)  (optional)

     - returns: RequestBuilder<HelpGetResponse> 
     */
    open class func getHelplistUsingGETWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String, lastId: Int64? = nil, size: Int32? = nil) -> RequestBuilder<HelpGetResponse> {
        let path = "/menus/help"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "lastId": lastId?.encodeToJSON(), 
            "size": size?.encodeToJSON()
        ])
        
        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<HelpGetResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     알림 리스트 가져오기
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter lastId: (query)  (optional)
     - parameter size: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getNoticesUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String, lastId: Int64? = nil, size: Int32? = nil, completion: @escaping ((_ data: NoticesGetResponse?,_ error: Error?) -> Void)) {
        getNoticesUsingGETWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, lastId: lastId, size: size).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     알림 리스트 가져오기
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter lastId: (query)  (optional)
     - parameter size: (query)  (optional)
     - returns: Observable<NoticesGetResponse>
     */
    open class func getNoticesUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String, lastId: Int64? = nil, size: Int32? = nil) -> Observable<NoticesGetResponse> {
        return Observable.create { observer -> Disposable in
            getNoticesUsingGET(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, lastId: lastId, size: size) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     알림 리스트 가져오기
     - GET /notices
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter lastId: (query)  (optional)
     - parameter size: (query)  (optional)

     - returns: RequestBuilder<NoticesGetResponse> 
     */
    open class func getNoticesUsingGETWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String, lastId: Int64? = nil, size: Int32? = nil) -> RequestBuilder<NoticesGetResponse> {
        let path = "/notices"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "lastId": lastId?.encodeToJSON(), 
            "size": size?.encodeToJSON()
        ])
        
        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<NoticesGetResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     회원 정보
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getProfileUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String, completion: @escaping ((_ data: ProfileGetResponse?,_ error: Error?) -> Void)) {
        getProfileUsingGETWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     회원 정보
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - returns: Observable<ProfileGetResponse>
     */
    open class func getProfileUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> Observable<ProfileGetResponse> {
        return Observable.create { observer -> Disposable in
            getProfileUsingGET(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     회원 정보
     - GET /accounts/profile
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 

     - returns: RequestBuilder<ProfileGetResponse> 
     */
    open class func getProfileUsingGETWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> RequestBuilder<ProfileGetResponse> {
        let path = "/accounts/profile"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ProfileGetResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     * enum for parameter type
     */
    public enum ModelType_getSeatsUsingGET: String { 
        case interpark = "INTERPARK"
        case yes24 = "YES24"
    }

    /**
     콘서트 좌석 정보 조회
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter type: (path) type 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getSeatsUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String, type: ModelType_getSeatsUsingGET, completion: @escaping ((_ data: ConcertsSeatGetResponse?,_ error: Error?) -> Void)) {
        getSeatsUsingGETWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, type: type).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     콘서트 좌석 정보 조회
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter type: (path) type 
     - returns: Observable<ConcertsSeatGetResponse>
     */
    open class func getSeatsUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String, type: ModelType_getSeatsUsingGET) -> Observable<ConcertsSeatGetResponse> {
        return Observable.create { observer -> Disposable in
            getSeatsUsingGET(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, type: type) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     콘서트 좌석 정보 조회
     - GET /concerts/seat/{type}
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter type: (path) type 

     - returns: RequestBuilder<ConcertsSeatGetResponse> 
     */
    open class func getSeatsUsingGETWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String, type: ModelType_getSeatsUsingGET) -> RequestBuilder<ConcertsSeatGetResponse> {
        var path = "/concerts/seat/{type}"
        path = path.replacingOccurrences(of: "{type}", with: "\(type.rawValue)", options: .literal, range: nil)
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ConcertsSeatGetResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     설정 정보 가져오기
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getSettingsUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String, completion: @escaping ((_ data: SettingsGetResponse?,_ error: Error?) -> Void)) {
        getSettingsUsingGETWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     설정 정보 가져오기
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - returns: Observable<SettingsGetResponse>
     */
    open class func getSettingsUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> Observable<SettingsGetResponse> {
        return Observable.create { observer -> Disposable in
            getSettingsUsingGET(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     설정 정보 가져오기
     - GET /settings
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 

     - returns: RequestBuilder<SettingsGetResponse> 
     */
    open class func getSettingsUsingGETWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> RequestBuilder<SettingsGetResponse> {
        let path = "/settings"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<SettingsGetResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     앱 버전 정보 가져오기
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getVersionUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String, completion: @escaping ((_ data: AppsGetResponse?,_ error: Error?) -> Void)) {
        getVersionUsingGETWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     앱 버전 정보 가져오기
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - returns: Observable<AppsGetResponse>
     */
    open class func getVersionUsingGET(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> Observable<AppsGetResponse> {
        return Observable.create { observer -> Disposable in
            getVersionUsingGET(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     앱 버전 정보 가져오기
     - GET /apps/version
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 

     - returns: RequestBuilder<AppsGetResponse> 
     */
    open class func getVersionUsingGETWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> RequestBuilder<AppsGetResponse> {
        let path = "/apps/version"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<AppsGetResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     알림 설정
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter alarm: (body) alarm 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func postAlarmsUsingPOST(xAPPVersion: String, xDevice: String, acceptLanguage: String, alarm: Bool, completion: @escaping ((_ data: CommonBooleanGetResponse?,_ error: Error?) -> Void)) {
        postAlarmsUsingPOSTWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, alarm: alarm).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     알림 설정
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter alarm: (body) alarm 
     - returns: Observable<CommonBooleanGetResponse>
     */
    open class func postAlarmsUsingPOST(xAPPVersion: String, xDevice: String, acceptLanguage: String, alarm: Bool) -> Observable<CommonBooleanGetResponse> {
        return Observable.create { observer -> Disposable in
            postAlarmsUsingPOST(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, alarm: alarm) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     알림 설정
     - POST /settings/alarm
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter alarm: (body) alarm 

     - returns: RequestBuilder<CommonBooleanGetResponse> 
     */
    open class func postAlarmsUsingPOSTWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String, alarm: Bool) -> RequestBuilder<CommonBooleanGetResponse> {
        let path = "/settings/alarm"
        let URLString = BoostMINIAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: alarm)

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<CommonBooleanGetResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }

    /**
     스킨 선택 설정
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter select: (body) select 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func postSkinsUsingPOST(xAPPVersion: String, xDevice: String, acceptLanguage: String, select: Int32, completion: @escaping ((_ data: CommonNumberGetResponse?,_ error: Error?) -> Void)) {
        postSkinsUsingPOSTWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, select: select).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     스킨 선택 설정
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter select: (body) select 
     - returns: Observable<CommonNumberGetResponse>
     */
    open class func postSkinsUsingPOST(xAPPVersion: String, xDevice: String, acceptLanguage: String, select: Int32) -> Observable<CommonNumberGetResponse> {
        return Observable.create { observer -> Disposable in
            postSkinsUsingPOST(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, select: select) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     스킨 선택 설정
     - POST /settings/skin
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter select: (body) select 

     - returns: RequestBuilder<CommonNumberGetResponse> 
     */
    open class func postSkinsUsingPOSTWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String, select: Int32) -> RequestBuilder<CommonNumberGetResponse> {
        let path = "/settings/skin"
        let URLString = BoostMINIAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: select)

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<CommonNumberGetResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }

    /**
     showResponseCode
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func showResponseCodeUsingHEAD(xAPPVersion: String, xDevice: String, acceptLanguage: String, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        showResponseCodeUsingHEADWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     showResponseCode
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - returns: Observable<String>
     */
    open class func showResponseCodeUsingHEAD(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> Observable<String> {
        return Observable.create { observer -> Disposable in
            showResponseCodeUsingHEAD(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     showResponseCode
     - HEAD /swagger/response/code
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 

     - returns: RequestBuilder<String> 
     */
    open class func showResponseCodeUsingHEADWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> RequestBuilder<String> {
        let path = "/swagger/response/code"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<String>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "HEAD", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     * enum for parameter socialType
     */
    public enum SocialType_signinUsingPOST: String { 
        case smtown = "SMTOWN"
        case facebook = "FACEBOOK"
        case twitter = "TWITTER"
        case google = "GOOGLE"
    }

    /**
     로그인
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter accessToken: (query)  
     - parameter socialType: (query)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func signinUsingPOST(xAPPVersion: String, xDevice: String, acceptLanguage: String, accessToken: String, socialType: SocialType_signinUsingPOST, completion: @escaping ((_ data: AccountsPostResponse?,_ error: Error?) -> Void)) {
        signinUsingPOSTWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, accessToken: accessToken, socialType: socialType).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     로그인
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter accessToken: (query)  
     - parameter socialType: (query)  
     - returns: Observable<AccountsPostResponse>
     */
    open class func signinUsingPOST(xAPPVersion: String, xDevice: String, acceptLanguage: String, accessToken: String, socialType: SocialType_signinUsingPOST) -> Observable<AccountsPostResponse> {
        return Observable.create { observer -> Disposable in
            signinUsingPOST(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, accessToken: accessToken, socialType: socialType) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     로그인
     - POST /accounts/signin
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter accessToken: (query)  
     - parameter socialType: (query)  

     - returns: RequestBuilder<AccountsPostResponse> 
     */
    open class func signinUsingPOSTWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String, accessToken: String, socialType: SocialType_signinUsingPOST) -> RequestBuilder<AccountsPostResponse> {
        let path = "/accounts/signin"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "accessToken": accessToken, 
            "socialType": socialType.rawValue
        ])
        
        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<AccountsPostResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     로그아웃
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func signoutUsingDELETE(xAPPVersion: String, xDevice: String, acceptLanguage: String, completion: @escaping ((_ error: Error?) -> Void)) {
        signoutUsingDELETEWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage).execute { (response, error) -> Void in
            completion(error);
        }
    }

    /**
     로그아웃
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - returns: Observable<Void>
     */
    open class func signoutUsingDELETE(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> Observable<Void> {
        return Observable.create { observer -> Disposable in
            signoutUsingDELETE(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage) { error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    // observer.on(.next())
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     로그아웃
     - DELETE /accounts/signout
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 

     - returns: RequestBuilder<Void> 
     */
    open class func signoutUsingDELETEWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> RequestBuilder<Void> {
        let path = "/accounts/signout"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = BoostMINIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     * enum for parameter socialType
     */
    public enum SocialType_signupUsingPOST: String { 
        case smtown = "SMTOWN"
        case facebook = "FACEBOOK"
        case twitter = "TWITTER"
        case google = "GOOGLE"
    }

    /**
     회원 가입
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter accessToken: (query)  
     - parameter socialType: (query)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func signupUsingPOST(xAPPVersion: String, xDevice: String, acceptLanguage: String, accessToken: String, socialType: SocialType_signupUsingPOST, completion: @escaping ((_ data: AccountsPostResponse?,_ error: Error?) -> Void)) {
        signupUsingPOSTWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, accessToken: accessToken, socialType: socialType).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     회원 가입
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter accessToken: (query)  
     - parameter socialType: (query)  
     - returns: Observable<AccountsPostResponse>
     */
    open class func signupUsingPOST(xAPPVersion: String, xDevice: String, acceptLanguage: String, accessToken: String, socialType: SocialType_signupUsingPOST) -> Observable<AccountsPostResponse> {
        return Observable.create { observer -> Disposable in
            signupUsingPOST(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage, accessToken: accessToken, socialType: socialType) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     회원 가입
     - POST /accounts/signup
     - examples: [{output=none}]
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter accessToken: (query)  
     - parameter socialType: (query)  

     - returns: RequestBuilder<AccountsPostResponse> 
     */
    open class func signupUsingPOSTWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String, accessToken: String, socialType: SocialType_signupUsingPOST) -> RequestBuilder<AccountsPostResponse> {
        let path = "/accounts/signup"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "accessToken": accessToken, 
            "socialType": socialType.rawValue
        ])
        
        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<AccountsPostResponse>.Type = BoostMINIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     탈퇴
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func withdrawUsingDELETE(xAPPVersion: String, xDevice: String, acceptLanguage: String, completion: @escaping ((_ error: Error?) -> Void)) {
        withdrawUsingDELETEWithRequestBuilder(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage).execute { (response, error) -> Void in
            completion(error);
        }
    }

    /**
     탈퇴
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 
     - returns: Observable<Void>
     */
    open class func withdrawUsingDELETE(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> Observable<Void> {
        return Observable.create { observer -> Disposable in
            withdrawUsingDELETE(xAPPVersion: xAPPVersion, xDevice: xDevice, acceptLanguage: acceptLanguage) { error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    // observer.on(.next())
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     탈퇴
     - DELETE /accounts/withdraw
     
     - parameter xAPPVersion: (header) app version 
     - parameter xDevice: (header) device/os information (informal) 
     - parameter acceptLanguage: (header) language-locale 

     - returns: RequestBuilder<Void> 
     */
    open class func withdrawUsingDELETEWithRequestBuilder(xAPPVersion: String, xDevice: String, acceptLanguage: String) -> RequestBuilder<Void> {
        let path = "/accounts/withdraw"
        let URLString = BoostMINIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "X-APP-Version": xAPPVersion,
            "X-Device": xDevice,
            "Accept-Language": acceptLanguage
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = BoostMINIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
